<?php

namespace KFI\GeoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        return parent::findBy($this->fixCriteria($criteria, $orderBy, $limit, $offset));
    }

    public function findOneBy(array $criteria)
    {
        return parent::findOneBy($this->fixCriteria($criteria));
    }

    public function find($id, $lockMode = \Doctrine\DBAL\LockMode::NONE, $lockVersion = null)
    {
        $ret = parent::find($id, $lockMode, $lockVersion);

        return $ret->getDeleted() ? null : $ret;
    }

    private function fixCriteria(array $criteria)
    {
        //Unless explicitly requested to return deleted items, we want to return non-deleted items by default
        if(isset($criteria['deleted'])){
            if($criteria['deleted'] == 'any'){
                unset($criteria['deleted']);
            }
        }else{
            $criteria['deleted'] = false;
        }

        return $criteria;
    }
}
