<?php

namespace KFI\GeoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TownItalyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TownItalyRepository extends EntityRepository
{
}
