DROP TABLE IF EXISTS `kfi_geo_country`;

CREATE TABLE `kfi_geo_country` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code3` varchar(3) COLLATE utf8_unicode_ci NOT NULL,
  `code2` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `name` varchar(52) COLLATE utf8_unicode_ci NOT NULL,
  `continent` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `continentRegion` varchar(26) COLLATE utf8_unicode_ci NOT NULL,
  `localName` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `deleted` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=895 ;

INSERT INTO `kfi_geo_country` (`id`, `code3`, `code2`, `name`, `continent`, `continentRegion`, `localName`, `deleted`) VALUES
(4, 'AFG', 'AF', 'Afghanistan', 'Asia', 'Southern and Central Asia', 'Afganistan/Afqanestan', 0),
(8, 'ALB', 'AL', 'Albania', 'Europe', 'Southern Europe', 'ShqipÃ«ria', 0),
(10, 'ATA', 'AQ', 'Antarctica', 'Antarctica', 'Antarctica', 'Antarctica', 0),
(12, 'DZA', 'DZ', 'Algeria', 'Africa', 'Northern Africa', 'Al-Jazaâ€™ir/AlgÃ©rie', 0),
(16, 'ASM', 'AS', 'American Samoa', 'Oceania', 'Polynesia', 'Amerika Samoa', 0),
(20, 'AND', 'AD', 'Andorra', 'Europe', 'Southern Europe', 'Andorra', 0),
(24, 'AGO', 'AO', 'Angola', 'Africa', 'Central Africa', 'Angola', 0),
(28, 'ATG', 'AG', 'Antigua and Barbuda', 'North America', 'Caribbean', 'Antigua and Barbuda', 0),
(31, 'AZE', 'AZ', 'Azerbaijan', 'Asia', 'Middle East', 'AzÃ¤rbaycan', 0),
(32, 'ARG', 'AR', 'Argentina', 'South America', 'South America', 'Argentina', 0),
(36, 'AUS', 'AU', 'Australia', 'Oceania', 'Australia and New Zealand', 'Australia', 0),
(40, 'AUT', 'AT', 'Austria', 'Europe', 'Western Europe', 'Ã–sterreich', 0),
(44, 'BHS', 'BS', 'Bahamas', 'North America', 'Caribbean', 'The Bahamas', 0),
(48, 'BHR', 'BH', 'Bahrain', 'Asia', 'Middle East', 'Al-Bahrayn', 0),
(50, 'BGD', 'BD', 'Bangladesh', 'Asia', 'Southern and Central Asia', 'Bangladesh', 0),
(51, 'ARM', 'AM', 'Armenia', 'Asia', 'Middle East', 'Hajastan', 0),
(52, 'BRB', 'BB', 'Barbados', 'North America', 'Caribbean', 'Barbados', 0),
(56, 'BEL', 'BE', 'Belgium', 'Europe', 'Western Europe', 'BelgiÃ«/Belgique', 0),
(60, 'BMU', 'BM', 'Bermuda', 'North America', 'North America', 'Bermuda', 0),
(64, 'BTN', 'BT', 'Bhutan', 'Asia', 'Southern and Central Asia', 'Druk-Yul', 0),
(68, 'BOL', 'BO', 'Bolivia', 'South America', 'South America', 'Bolivia', 0),
(70, 'BIH', 'BA', 'Bosnia and Herzegovina', 'Europe', 'Southern Europe', 'Bosna i Hercegovina', 0),
(72, 'BWA', 'BW', 'Botswana', 'Africa', 'Southern Africa', 'Botswana', 0),
(74, 'BVT', 'BV', 'Bouvet Island', 'Antarctica', 'Antarctica', 'Bouvet Island', 0),
(76, 'BRA', 'BR', 'Brazil', 'South America', 'South America', 'Brasil', 0),
(84, 'BLZ', 'BZ', 'Belize', 'North America', 'Central America', 'Belize', 0),
(86, 'IOT', 'IO', 'British Indian Ocean Territory', 'Africa', 'Eastern Africa', 'British Indian Ocean Territory', 0),
(90, 'SLB', 'SB', 'Solomon Islands', 'Oceania', 'Melanesia', 'Solomon Islands', 0),
(92, 'VGB', 'VG', 'Virgin Islands, British', 'North America', 'Caribbean', 'British Virgin Islands', 0),
(96, 'BRN', 'BN', 'Brunei', 'Asia', 'Southeast Asia', 'Brunei Darussalam', 0),
(100, 'BGR', 'BG', 'Bulgaria', 'Europe', 'Eastern Europe', 'Balgarija', 0),
(104, 'MMR', 'MM', 'Myanmar', 'Asia', 'Southeast Asia', 'Myanma Pye', 0),
(108, 'BDI', 'BI', 'Burundi', 'Africa', 'Eastern Africa', 'Burundi/Uburundi', 0),
(112, 'BLR', 'BY', 'Belarus', 'Europe', 'Eastern Europe', 'Belarus', 0),
(116, 'KHM', 'KH', 'Cambodia', 'Asia', 'Southeast Asia', 'KÃ¢mpuchÃ©a', 0),
(120, 'CMR', 'CM', 'Cameroon', 'Africa', 'Central Africa', 'Cameroun/Cameroon', 0),
(124, 'CAN', 'CA', 'Canada', 'North America', 'North America', 'Canada', 0),
(132, 'CPV', 'CV', 'Cape Verde', 'Africa', 'Western Africa', 'Cabo Verde', 0),
(136, 'CYM', 'KY', 'Cayman Islands', 'North America', 'Caribbean', 'Cayman Islands', 0),
(140, 'CAF', 'CF', 'Central African Republic', 'Africa', 'Central Africa', 'Centrafrique/BÃª-AfrÃ®ka', 0),
(144, 'LKA', 'LK', 'Sri Lanka', 'Asia', 'Southern and Central Asia', 'Sri Lanka/Ilankai', 0),
(148, 'TCD', 'TD', 'Chad', 'Africa', 'Central Africa', 'Tchad/Tshad', 0),
(152, 'CHL', 'CL', 'Chile', 'South America', 'South America', 'Chile', 0),
(156, 'CHN', 'CN', 'China', 'Asia', 'Eastern Asia', 'Zhongquo', 0),
(158, 'TWN', 'TW', 'Taiwan', 'Asia', 'Eastern Asia', 'Tâ€™ai-wan', 0),
(162, 'CXR', 'CX', 'Christmas Island', 'Oceania', 'Australia and New Zealand', 'Christmas Island', 0),
(166, 'CCK', 'CC', 'Cocos (Keeling) Islands', 'Oceania', 'Australia and New Zealand', 'Cocos (Keeling) Islands', 0),
(170, 'COL', 'CO', 'Colombia', 'South America', 'South America', 'Colombia', 0),
(174, 'COM', 'KM', 'Comoros', 'Africa', 'Eastern Africa', 'Komori/Comores', 0),
(175, 'MYT', 'YT', 'Mayotte', 'Africa', 'Eastern Africa', 'Mayotte', 0),
(178, 'COG', 'CG', 'Congo', 'Africa', 'Central Africa', 'Congo', 0),
(180, 'COD', 'CD', 'Congo, The Democratic Republic of the', 'Africa', 'Central Africa', 'RÃ©publique DÃ©mocratique du Congo', 0),
(184, 'COK', 'CK', 'Cook Islands', 'Oceania', 'Polynesia', 'The Cook Islands', 0),
(188, 'CRI', 'CR', 'Costa Rica', 'North America', 'Central America', 'Costa Rica', 0),
(191, 'HRV', 'HR', 'Croatia', 'Europe', 'Southern Europe', 'Hrvatska', 0),
(192, 'CUB', 'CU', 'Cuba', 'North America', 'Caribbean', 'Cuba', 0),
(196, 'CYP', 'CY', 'Cyprus', 'Asia', 'Middle East', 'KÃ½pros/Kibris', 0),
(203, 'CZE', 'CZ', 'Czech Republic', 'Europe', 'Eastern Europe', 'Â¸esko', 0),
(204, 'BEN', 'BJ', 'Benin', 'Africa', 'Western Africa', 'BÃ©nin', 0),
(208, 'DNK', 'DK', 'Denmark', 'Europe', 'Nordic Countries', 'Danmark', 0),
(212, 'DMA', 'DM', 'Dominica', 'North America', 'Caribbean', 'Dominica', 0),
(214, 'DOM', 'DO', 'Dominican Republic', 'North America', 'Caribbean', 'RepÃºblica Dominicana', 0),
(218, 'ECU', 'EC', 'Ecuador', 'South America', 'South America', 'Ecuador', 0),
(222, 'SLV', 'SV', 'El Salvador', 'North America', 'Central America', 'El Salvador', 0),
(226, 'GNQ', 'GQ', 'Equatorial Guinea', 'Africa', 'Central Africa', 'Guinea Ecuatorial', 0),
(231, 'ETH', 'ET', 'Ethiopia', 'Africa', 'Eastern Africa', 'YeItyopÂ´iya', 0),
(232, 'ERI', 'ER', 'Eritrea', 'Africa', 'Eastern Africa', 'Ertra', 0),
(233, 'EST', 'EE', 'Estonia', 'Europe', 'Baltic Countries', 'Eesti', 0),
(234, 'FRO', 'FO', 'Faroe Islands', 'Europe', 'Nordic Countries', 'FÃ¸royar', 0),
(238, 'FLK', 'FK', 'Falkland Islands', 'South America', 'South America', 'Falkland Islands', 0),
(239, 'SGS', 'GS', 'South Georgia and the South Sandwich Islands', 'Antarctica', 'Antarctica', 'South Georgia and the South Sandwich Islands', 0),
(242, 'FJI', 'FJ', 'Fiji Islands', 'Oceania', 'Melanesia', 'Fiji Islands', 0),
(246, 'FIN', 'FI', 'Finland', 'Europe', 'Nordic Countries', 'Suomi', 0),
(250, 'FRA', 'FR', 'France', 'Europe', 'Western Europe', 'France', 0),
(254, 'GUF', 'GF', 'French Guiana', 'South America', 'South America', 'Guyane franÃ§aise', 0),
(258, 'PYF', 'PF', 'French Polynesia', 'Oceania', 'Polynesia', 'PolynÃ©sie franÃ§aise', 0),
(260, 'ATF', 'TF', 'French Southern territories', 'Antarctica', 'Antarctica', 'Terres australes franÃ§aises', 0),
(262, 'DJI', 'DJ', 'Djibouti', 'Africa', 'Eastern Africa', 'Djibouti/Jibuti', 0),
(266, 'GAB', 'GA', 'Gabon', 'Africa', 'Central Africa', 'Le Gabon', 0),
(268, 'GEO', 'GE', 'Georgia', 'Asia', 'Middle East', 'Sakartvelo', 0),
(270, 'GMB', 'GM', 'Gambia', 'Africa', 'Western Africa', 'The Gambia', 0),
(275, 'PSE', 'PS', 'Palestine', 'Asia', 'Middle East', 'Filastin', 0),
(276, 'DEU', 'DE', 'Germany', 'Europe', 'Western Europe', 'Deutschland', 0),
(288, 'GHA', 'GH', 'Ghana', 'Africa', 'Western Africa', 'Ghana', 0),
(292, 'GIB', 'GI', 'Gibraltar', 'Europe', 'Southern Europe', 'Gibraltar', 0),
(296, 'KIR', 'KI', 'Kiribati', 'Oceania', 'Micronesia', 'Kiribati', 0),
(300, 'GRC', 'GR', 'Greece', 'Europe', 'Southern Europe', 'EllÃ¡da', 0),
(304, 'GRL', 'GL', 'Greenland', 'North America', 'North America', 'Kalaallit Nunaat/GrÃ¸nland', 0),
(308, 'GRD', 'GD', 'Grenada', 'North America', 'Caribbean', 'Grenada', 0),
(312, 'GLP', 'GP', 'Guadeloupe', 'North America', 'Caribbean', 'Guadeloupe', 0),
(316, 'GUM', 'GU', 'Guam', 'Oceania', 'Micronesia', 'Guam', 0),
(320, 'GTM', 'GT', 'Guatemala', 'North America', 'Central America', 'Guatemala', 0),
(324, 'GIN', 'GN', 'Guinea', 'Africa', 'Western Africa', 'GuinÃ©e', 0),
(328, 'GUY', 'GY', 'Guyana', 'South America', 'South America', 'Guyana', 0),
(332, 'HTI', 'HT', 'Haiti', 'North America', 'Caribbean', 'HaÃ¯ti/Dayti', 0),
(334, 'HMD', 'HM', 'Heard Island and McDonald Islands', 'Antarctica', 'Antarctica', 'Heard and McDonald Islands', 0),
(336, 'VAT', 'VA', 'Holy See (Vatican City State)', 'Europe', 'Southern Europe', 'Santa Sede/Città  del Vaticano', 0),
(340, 'HND', 'HN', 'Honduras', 'North America', 'Central America', 'Honduras', 0),
(344, 'HKG', 'HK', 'Hong Kong', 'Asia', 'Eastern Asia', 'Xianggang/Hong Kong', 0),
(348, 'HUN', 'HU', 'Hungary', 'Europe', 'Eastern Europe', 'MagyarorszÃ¡g', 0),
(352, 'ISL', 'IS', 'Iceland', 'Europe', 'Nordic Countries', 'Ãsland', 0),
(356, 'IND', 'IN', 'India', 'Asia', 'Southern and Central Asia', 'Bharat/India', 0),
(360, 'IDN', 'ID', 'Indonesia', 'Asia', 'Southeast Asia', 'Indonesia', 0),
(364, 'IRN', 'IR', 'Iran', 'Asia', 'Southern and Central Asia', 'Iran', 0),
(368, 'IRQ', 'IQ', 'Iraq', 'Asia', 'Middle East', 'Al-Â´Iraq', 0),
(372, 'IRL', 'IE', 'Ireland', 'Europe', 'British Islands', 'Ireland/Ã‰ire', 0),
(376, 'ISR', 'IL', 'Israel', 'Asia', 'Middle East', 'Yisraâ€™el/Israâ€™il', 0),
(380, 'ITA', 'IT', 'Italy', 'Europe', 'Southern Europe', 'Italia', 0),
(384, 'CIV', 'CI', 'CÃ´te dâ€™Ivoire', 'Africa', 'Western Africa', 'CÃ´te dâ€™Ivoire', 0),
(388, 'JAM', 'JM', 'Jamaica', 'North America', 'Caribbean', 'Jamaica', 0),
(392, 'JPN', 'JP', 'Japan', 'Asia', 'Eastern Asia', 'Nihon/Nippon', 0),
(398, 'KAZ', 'KZ', 'Kazakstan', 'Asia', 'Southern and Central Asia', 'Qazaqstan', 0),
(400, 'JOR', 'JO', 'Jordan', 'Asia', 'Middle East', 'Al-Urdunn', 0),
(404, 'KEN', 'KE', 'Kenya', 'Africa', 'Eastern Africa', 'Kenya', 0),
(408, 'PRK', 'KP', 'North Korea', 'Asia', 'Eastern Asia', 'Choson Minjujuui InÂ´min Konghwaguk (Bukhan)', 0),
(410, 'KOR', 'KR', 'South Korea', 'Asia', 'Eastern Asia', 'Taehan Minâ€™guk (Namhan)', 0),
(414, 'KWT', 'KW', 'Kuwait', 'Asia', 'Middle East', 'Al-Kuwayt', 0),
(417, 'KGZ', 'KG', 'Kyrgyzstan', 'Asia', 'Southern and Central Asia', 'Kyrgyzstan', 0),
(418, 'LAO', 'LA', 'Laos', 'Asia', 'Southeast Asia', 'Lao', 0),
(422, 'LBN', 'LB', 'Lebanon', 'Asia', 'Middle East', 'Lubnan', 0),
(426, 'LSO', 'LS', 'Lesotho', 'Africa', 'Southern Africa', 'Lesotho', 0),
(428, 'LVA', 'LV', 'Latvia', 'Europe', 'Baltic Countries', 'Latvija', 0),
(430, 'LBR', 'LR', 'Liberia', 'Africa', 'Western Africa', 'Liberia', 0),
(434, 'LBY', 'LY', 'Libyan Arab Jamahiriya', 'Africa', 'Northern Africa', 'Libiya', 0),
(438, 'LIE', 'LI', 'Liechtenstein', 'Europe', 'Western Europe', 'Liechtenstein', 0),
(440, 'LTU', 'LT', 'Lithuania', 'Europe', 'Baltic Countries', 'Lietuva', 0),
(442, 'LUX', 'LU', 'Luxembourg', 'Europe', 'Western Europe', 'Luxembourg/LÃ«tzebuerg', 0),
(446, 'MAC', 'MO', 'Macao', 'Asia', 'Eastern Asia', 'Macau/Aomen', 0),
(450, 'MDG', 'MG', 'Madagascar', 'Africa', 'Eastern Africa', 'Madagasikara/Madagascar', 0),
(454, 'MWI', 'MW', 'Malawi', 'Africa', 'Eastern Africa', 'Malawi', 0),
(458, 'MYS', 'MY', 'Malaysia', 'Asia', 'Southeast Asia', 'Malaysia', 0),
(462, 'MDV', 'MV', 'Maldives', 'Asia', 'Southern and Central Asia', 'Dhivehi Raajje/Maldives', 0),
(466, 'MLI', 'ML', 'Mali', 'Africa', 'Western Africa', 'Mali', 0),
(470, 'MLT', 'MT', 'Malta', 'Europe', 'Southern Europe', 'Malta', 0),
(474, 'MTQ', 'MQ', 'Martinique', 'North America', 'Caribbean', 'Martinique', 0),
(478, 'MRT', 'MR', 'Mauritania', 'Africa', 'Western Africa', 'Muritaniya/Mauritanie', 0),
(480, 'MUS', 'MU', 'Mauritius', 'Africa', 'Eastern Africa', 'Mauritius', 0),
(484, 'MEX', 'MX', 'Mexico', 'North America', 'Central America', 'MÃ©xico', 0),
(492, 'MCO', 'MC', 'Monaco', 'Europe', 'Western Europe', 'Monaco', 0),
(496, 'MNG', 'MN', 'Mongolia', 'Asia', 'Eastern Asia', 'Mongol Uls', 0),
(498, 'MDA', 'MD', 'Moldova', 'Europe', 'Eastern Europe', 'Moldova', 0),
(500, 'MSR', 'MS', 'Montserrat', 'North America', 'Caribbean', 'Montserrat', 0),
(504, 'MAR', 'MA', 'Morocco', 'Africa', 'Northern Africa', 'Al-Maghrib', 0),
(508, 'MOZ', 'MZ', 'Mozambique', 'Africa', 'Eastern Africa', 'MoÃ§ambique', 0),
(512, 'OMN', 'OM', 'Oman', 'Asia', 'Middle East', 'Â´Uman', 0),
(516, 'NAM', 'NA', 'Namibia', 'Africa', 'Southern Africa', 'Namibia', 0),
(520, 'NRU', 'NR', 'Nauru', 'Oceania', 'Micronesia', 'Naoero/Nauru', 0),
(524, 'NPL', 'NP', 'Nepal', 'Asia', 'Southern and Central Asia', 'Nepal', 0),
(528, 'NLD', 'NL', 'Netherlands', 'Europe', 'Western Europe', 'Nederland', 0),
(530, 'ANT', 'AN', 'Netherlands Antilles', 'North America', 'Caribbean', 'Nederlandse Antillen', 0),
(533, 'ABW', 'AW', 'Aruba', 'North America', 'Caribbean', 'Aruba', 0),
(540, 'NCL', 'NC', 'New Caledonia', 'Oceania', 'Melanesia', 'Nouvelle-CalÃ©donie', 0),
(548, 'VUT', 'VU', 'Vanuatu', 'Oceania', 'Melanesia', 'Vanuatu', 0),
(554, 'NZL', 'NZ', 'New Zealand', 'Oceania', 'Australia and New Zealand', 'New Zealand/Aotearoa', 0),
(558, 'NIC', 'NI', 'Nicaragua', 'North America', 'Central America', 'Nicaragua', 0),
(562, 'NER', 'NE', 'Niger', 'Africa', 'Western Africa', 'Niger', 0),
(566, 'NGA', 'NG', 'Nigeria', 'Africa', 'Western Africa', 'Nigeria', 0),
(570, 'NIU', 'NU', 'Niue', 'Oceania', 'Polynesia', 'Niue', 0),
(574, 'NFK', 'NF', 'Norfolk Island', 'Oceania', 'Australia and New Zealand', 'Norfolk Island', 0),
(578, 'NOR', 'NO', 'Norway', 'Europe', 'Nordic Countries', 'Norge', 0),
(580, 'MNP', 'MP', 'Northern Mariana Islands', 'Oceania', 'Micronesia', 'Northern Mariana Islands', 0),
(581, 'UMI', 'UM', 'United States Minor Outlying Islands', 'Oceania', 'Micronesia/Caribbean', 'United States Minor Outlying Islands', 0),
(583, 'FSM', 'FM', 'Micronesia, Federated States of', 'Oceania', 'Micronesia', 'Micronesia', 0),
(584, 'MHL', 'MH', 'Marshall Islands', 'Oceania', 'Micronesia', 'Marshall Islands/Majol', 0),
(585, 'PLW', 'PW', 'Palau', 'Oceania', 'Micronesia', 'Belau/Palau', 0),
(586, 'PAK', 'PK', 'Pakistan', 'Asia', 'Southern and Central Asia', 'Pakistan', 0),
(591, 'PAN', 'PA', 'Panama', 'North America', 'Central America', 'PanamÃ¡', 0),
(598, 'PNG', 'PG', 'Papua New Guinea', 'Oceania', 'Melanesia', 'Papua New Guinea/Papua Niugini', 0),
(600, 'PRY', 'PY', 'Paraguay', 'South America', 'South America', 'Paraguay', 0),
(604, 'PER', 'PE', 'Peru', 'South America', 'South America', 'PerÃº/Piruw', 0),
(608, 'PHL', 'PH', 'Philippines', 'Asia', 'Southeast Asia', 'Pilipinas', 0),
(612, 'PCN', 'PN', 'Pitcairn', 'Oceania', 'Polynesia', 'Pitcairn', 0),
(616, 'POL', 'PL', 'Poland', 'Europe', 'Eastern Europe', 'Polska', 0),
(620, 'PRT', 'PT', 'Portugal', 'Europe', 'Southern Europe', 'Portugal', 0),
(624, 'GNB', 'GW', 'Guinea-Bissau', 'Africa', 'Western Africa', 'GuinÃ©-Bissau', 0),
(626, 'TMP', 'TP', 'East Timor', 'Asia', 'Southeast Asia', 'Timor Timur', 0),
(630, 'PRI', 'PR', 'Puerto Rico', 'North America', 'Caribbean', 'Puerto Rico', 0),
(634, 'QAT', 'QA', 'Qatar', 'Asia', 'Middle East', 'Qatar', 0),
(638, 'REU', 'RE', 'RÃ©union', 'Africa', 'Eastern Africa', 'RÃ©union', 0),
(642, 'ROM', 'RO', 'Romania', 'Europe', 'Eastern Europe', 'RomÃ¢nia', 0),
(643, 'RUS', 'RU', 'Russian Federation', 'Europe', 'Eastern Europe', 'Rossija', 0),
(646, 'RWA', 'RW', 'Rwanda', 'Africa', 'Eastern Africa', 'Rwanda/Urwanda', 0),
(654, 'SHN', 'SH', 'Saint Helena', 'Africa', 'Western Africa', 'Saint Helena', 0),
(659, 'KNA', 'KN', 'Saint Kitts and Nevis', 'North America', 'Caribbean', 'Saint Kitts and Nevis', 0),
(660, 'AIA', 'AI', 'Anguilla', 'North America', 'Caribbean', 'Anguilla', 0),
(662, 'LCA', 'LC', 'Saint Lucia', 'North America', 'Caribbean', 'Saint Lucia', 0),
(666, 'SPM', 'PM', 'Saint Pierre and Miquelon', 'North America', 'North America', 'Saint-Pierre-et-Miquelon', 0),
(670, 'VCT', 'VC', 'Saint Vincent and the Grenadines', 'North America', 'Caribbean', 'Saint Vincent and the Grenadines', 0),
(674, 'SMR', 'SM', 'San Marino', 'Europe', 'Southern Europe', 'San Marino', 0),
(678, 'STP', 'ST', 'Sao Tome and Principe', 'Africa', 'Central Africa', 'SÃ£o TomÃ© e PrÃ­ncipe', 0),
(682, 'SAU', 'SA', 'Saudi Arabia', 'Asia', 'Middle East', 'Al-Â´Arabiya as-SaÂ´udiya', 0),
(686, 'SEN', 'SN', 'Senegal', 'Africa', 'Western Africa', 'SÃ©nÃ©gal/Sounougal', 0),
(688, 'SRB', 'RS', 'Serbia', 'Europe', 'Southern Europe', 'Republika Srbija', 0),
(690, 'SYC', 'SC', 'Seychelles', 'Africa', 'Eastern Africa', 'Sesel/Seychelles', 0),
(694, 'SLE', 'SL', 'Sierra Leone', 'Africa', 'Western Africa', 'Sierra Leone', 0),
(702, 'SGP', 'SG', 'Singapore', 'Asia', 'Southeast Asia', 'Singapore/Singapura/Xinjiapo/Singapur', 0),
(703, 'SVK', 'SK', 'Slovakia', 'Europe', 'Eastern Europe', 'Slovensko', 0),
(704, 'VNM', 'VN', 'Vietnam', 'Asia', 'Southeast Asia', 'ViÃªt Nam', 0),
(705, 'SVN', 'SI', 'Slovenia', 'Europe', 'Southern Europe', 'Slovenija', 0),
(706, 'SOM', 'SO', 'Somalia', 'Africa', 'Eastern Africa', 'Soomaaliya', 0),
(710, 'ZAF', 'ZA', 'South Africa', 'Africa', 'Southern Africa', 'South Africa', 0),
(716, 'ZWE', 'ZW', 'Zimbabwe', 'Africa', 'Eastern Africa', 'Zimbabwe', 0),
(724, 'ESP', 'ES', 'Spain', 'Europe', 'Southern Europe', 'EspaÃ±a', 0),
(732, 'ESH', 'EH', 'Western Sahara', 'Africa', 'Northern Africa', 'As-Sahrawiya', 0),
(736, 'SDN', 'SD', 'Sudan', 'Africa', 'Northern Africa', 'As-Sudan', 0),
(740, 'SUR', 'SR', 'Suriname', 'South America', 'South America', 'Suriname', 0),
(744, 'SJM', 'SJ', 'Svalbard and Jan Mayen', 'Europe', 'Nordic Countries', 'Svalbard og Jan Mayen', 0),
(748, 'SWZ', 'SZ', 'Swaziland', 'Africa', 'Southern Africa', 'kaNgwane', 0),
(752, 'SWE', 'SE', 'Sweden', 'Europe', 'Nordic Countries', 'Sverige', 0),
(756, 'CHE', 'CH', 'Switzerland', 'Europe', 'Western Europe', 'Schweiz/Suisse/Svizzera/Svizra', 0),
(760, 'SYR', 'SY', 'Syria', 'Asia', 'Middle East', 'Suriya', 0),
(762, 'TJK', 'TJ', 'Tajikistan', 'Asia', 'Southern and Central Asia', 'ToÃ§ikiston', 0),
(764, 'THA', 'TH', 'Thailand', 'Asia', 'Southeast Asia', 'Prathet Thai', 0),
(768, 'TGO', 'TG', 'Togo', 'Africa', 'Western Africa', 'Togo', 0),
(772, 'TKL', 'TK', 'Tokelau', 'Oceania', 'Polynesia', 'Tokelau', 0),
(776, 'TON', 'TO', 'Tonga', 'Oceania', 'Polynesia', 'Tonga', 0),
(780, 'TTO', 'TT', 'Trinidad and Tobago', 'North America', 'Caribbean', 'Trinidad and Tobago', 0),
(784, 'ARE', 'AE', 'United Arab Emirates', 'Asia', 'Middle East', 'Al-Imarat al-Â´Arabiya al-Muttahida', 0),
(788, 'TUN', 'TN', 'Tunisia', 'Africa', 'Northern Africa', 'Tunis/Tunisie', 0),
(792, 'TUR', 'TR', 'Turkey', 'Asia', 'Middle East', 'TÃ¼rkiye', 0),
(795, 'TKM', 'TM', 'Turkmenistan', 'Asia', 'Southern and Central Asia', 'TÃ¼rkmenostan', 0),
(796, 'TCA', 'TC', 'Turks and Caicos Islands', 'North America', 'Caribbean', 'The Turks and Caicos Islands', 0),
(798, 'TUV', 'TV', 'Tuvalu', 'Oceania', 'Polynesia', 'Tuvalu', 0),
(800, 'UGA', 'UG', 'Uganda', 'Africa', 'Eastern Africa', 'Uganda', 0),
(804, 'UKR', 'UA', 'Ukraine', 'Europe', 'Eastern Europe', 'Ukrajina', 0),
(807, 'MKD', 'MK', 'Macedonia', 'Europe', 'Southern Europe', 'Makedonija', 0),
(818, 'EGY', 'EG', 'Egypt', 'Africa', 'Northern Africa', 'Misr', 0),
(826, 'GBR', 'GB', 'United Kingdom', 'Europe', 'British Islands', 'United Kingdom', 0),
(834, 'TZA', 'TZ', 'Tanzania', 'Africa', 'Eastern Africa', 'Tanzania', 0),
(840, 'USA', 'US', 'United States', 'North America', 'North America', 'United States', 0),
(850, 'VIR', 'VI', 'Virgin Islands, U.S.', 'North America', 'Caribbean', 'Virgin Islands of the United States', 0),
(854, 'BFA', 'BF', 'Burkina Faso', 'Africa', 'Western Africa', 'Burkina Faso', 0),
(858, 'URY', 'UY', 'Uruguay', 'South America', 'South America', 'Uruguay', 0),
(860, 'UZB', 'UZ', 'Uzbekistan', 'Asia', 'Southern and Central Asia', 'Uzbekiston', 0),
(862, 'VEN', 'VE', 'Venezuela', 'South America', 'South America', 'Venezuela', 0),
(876, 'WLF', 'WF', 'Wallis and Futuna', 'Oceania', 'Polynesia', 'Wallis-et-Futuna', 0),
(882, 'WSM', 'WS', 'Samoa', 'Oceania', 'Polynesia', 'Samoa', 0),
(887, 'YEM', 'YE', 'Yemen', 'Asia', 'Middle East', 'Al-Yaman', 0),
(891, 'YUG', 'YU', 'Yugoslavia', 'Europe', 'Southern Europe', 'Jugoslavija', 1),
(894, 'ZMB', 'ZM', 'Zambia', 'Africa', 'Eastern Africa', 'Zambia', 0);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
